FROM centos
RUN mkdir /opt/tomcat/
WORKDIR /opt/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.1/bin/apache-tomcat-10.1.1.tar.gz .
RUN tar xvfz apache*.tar.gz \
  &&  mv apache-tomcat-10.1.1/* /opt/tomcat/.  \
  &&  yum -yinstall java  \
  && java -version 
EXPOSE 8080
#CMD sh /opt/tomcat/bin/catalina.sh run
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
